CREATE TABLE [dbo].[tbLugares]
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[ID_TAG] INT NOT NULL,
	[NOME] VARCHAR(50) NOT NULL,
	[DESCRICAO] VARCHAR(50) NOT NULL,

	FOREIGN KEY ([ID_TAG]) REFERENCES [tbTags]([ID]) ON DELETE CASCADE,

)
