CREATE TABLE [tbTags]
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[TAG] VARCHAR(50) UNIQUE NOT NULL,
	[ID_ESTABELECIMENTO] INT NOT NULL,

	FOREIGN KEY ([ID_ESTABELECIMENTO]) REFERENCES [tbEstabelecimento]([ID]),
)
GO
CREATE  INDEX [IX_tbTags_Column] ON [tbTags] ([TAG])
